//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TablCHast3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Препод.
    /// </summary>
    // *** Start programmer edit section *** (Препод CustomAttributes)

    // *** End programmer edit section *** (Препод CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПреподE", new string[] {
            "ФИО as \'ФИО\'"})]
    [AssociatedDetailViewAttribute("ПреподE", "Город", "ГородE", true, "", "Город", true, new string[] {
            ""})]
    [View("ПреподL", new string[] {
            "ФИО as \'ФИО\'"})]
    [AssociatedDetailViewAttribute("ПреподL", "Город", "ГородL", true, "", "", true, new string[] {
            ""})]
    public class Препод : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.TablCHast3.DetailArrayOfГород fГород;
        
        // *** Start programmer edit section *** (Препод CustomMembers)

        // *** End programmer edit section *** (Препод CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Препод.ФИО CustomAttributes)

        // *** End programmer edit section *** (Препод.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Препод.ФИО Get start)

                // *** End programmer edit section *** (Препод.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Препод.ФИО Get end)

                // *** End programmer edit section *** (Препод.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Препод.ФИО Set start)

                // *** End programmer edit section *** (Препод.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Препод.ФИО Set end)

                // *** End programmer edit section *** (Препод.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Препод.
        /// </summary>
        // *** Start programmer edit section *** (Препод.Город CustomAttributes)

        // *** End programmer edit section *** (Препод.Город CustomAttributes)
        public virtual IIS.TablCHast3.DetailArrayOfГород Город
        {
            get
            {
                // *** Start programmer edit section *** (Препод.Город Get start)

                // *** End programmer edit section *** (Препод.Город Get start)
                if ((this.fГород == null))
                {
                    this.fГород = new IIS.TablCHast3.DetailArrayOfГород(this);
                }
                IIS.TablCHast3.DetailArrayOfГород result = this.fГород;
                // *** Start programmer edit section *** (Препод.Город Get end)

                // *** End programmer edit section *** (Препод.Город Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Препод.Город Set start)

                // *** End programmer edit section *** (Препод.Город Set start)
                this.fГород = value;
                // *** Start programmer edit section *** (Препод.Город Set end)

                // *** End programmer edit section *** (Препод.Город Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПреподE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПреподE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПреподE", typeof(IIS.TablCHast3.Препод));
                }
            }
            
            /// <summary>
            /// "ПреподL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПреподL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПреподL", typeof(IIS.TablCHast3.Препод));
                }
            }
        }
    }
}
