//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.TablCHast3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ученик.
    /// </summary>
    // *** Start programmer edit section *** (Ученик CustomAttributes)

    // *** End programmer edit section *** (Ученик CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УченикE", new string[] {
            "ФИО as \'ФИО\'",
            "Препод as \'Препод\'",
            "Препод.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Препод.ФИО"})]
    [AssociatedDetailViewAttribute("УченикE", "Родитель", "РодительE", true, "", "Родитель", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("УченикE", "Препод", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("УченикL", new string[] {
            "ФИО as \'ФИО\'",
            "Препод.ФИО as \'ФИО\'"})]
    public class Ученик : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.TablCHast3.Препод fПрепод;
        
        private IIS.TablCHast3.DetailArrayOfРодитель fРодитель;
        
        // *** Start programmer edit section *** (Ученик CustomMembers)

        // *** End programmer edit section *** (Ученик CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.ФИО CustomAttributes)

        // *** End programmer edit section *** (Ученик.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.ФИО Get start)

                // *** End programmer edit section *** (Ученик.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Ученик.ФИО Get end)

                // *** End programmer edit section *** (Ученик.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.ФИО Set start)

                // *** End programmer edit section *** (Ученик.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Ученик.ФИО Set end)

                // *** End programmer edit section *** (Ученик.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Ученик.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.Препод CustomAttributes)

        // *** End programmer edit section *** (Ученик.Препод CustomAttributes)
        [PropertyStorage(new string[] {
                "Препод"})]
        [NotNull()]
        public virtual IIS.TablCHast3.Препод Препод
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.Препод Get start)

                // *** End programmer edit section *** (Ученик.Препод Get start)
                IIS.TablCHast3.Препод result = this.fПрепод;
                // *** Start programmer edit section *** (Ученик.Препод Get end)

                // *** End programmer edit section *** (Ученик.Препод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.Препод Set start)

                // *** End programmer edit section *** (Ученик.Препод Set start)
                this.fПрепод = value;
                // *** Start programmer edit section *** (Ученик.Препод Set end)

                // *** End programmer edit section *** (Ученик.Препод Set end)
            }
        }
        
        /// <summary>
        /// Ученик.
        /// </summary>
        // *** Start programmer edit section *** (Ученик.Родитель CustomAttributes)

        // *** End programmer edit section *** (Ученик.Родитель CustomAttributes)
        public virtual IIS.TablCHast3.DetailArrayOfРодитель Родитель
        {
            get
            {
                // *** Start programmer edit section *** (Ученик.Родитель Get start)

                // *** End programmer edit section *** (Ученик.Родитель Get start)
                if ((this.fРодитель == null))
                {
                    this.fРодитель = new IIS.TablCHast3.DetailArrayOfРодитель(this);
                }
                IIS.TablCHast3.DetailArrayOfРодитель result = this.fРодитель;
                // *** Start programmer edit section *** (Ученик.Родитель Get end)

                // *** End programmer edit section *** (Ученик.Родитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ученик.Родитель Set start)

                // *** End programmer edit section *** (Ученик.Родитель Set start)
                this.fРодитель = value;
                // *** Start programmer edit section *** (Ученик.Родитель Set end)

                // *** End programmer edit section *** (Ученик.Родитель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УченикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УченикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УченикE", typeof(IIS.TablCHast3.Ученик));
                }
            }
            
            /// <summary>
            /// "УченикL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УченикL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УченикL", typeof(IIS.TablCHast3.Ученик));
                }
            }
        }
    }
}
